apiVersion: v1
kind: Config
clusters:
- name: my-cluster
  cluster:
    server: https://my-cluster-api-server.example.com
    certificate-authority-data: <base64-encoded certificate authority data>
users:
- name: my-user
  user:
    client-certificate-data: <base64-encoded client certificate data>
    client-key-data: <base64-encoded client key data>
contexts:
- name: my-context
  context:
    cluster: my-cluster
    user: my-user
    namespace: my-namespace
current-context: my-context